using Mori.Ros2Sharp.Msg;

// ros2msggen: typed C# message, service, and action classes from ROS 2 .msg, .srv, and
// .action files.
//
// Inputs are interface files or directories laid out ROS-style (<package>/msg/<Name>.msg,
// <package>/srv/<Name>.srv, <package>/action/<Name>.action, or <package>/<Name>.msg). Nested
// types resolve against the inputs first, then the embedded common set (builtin_interfaces,
// std_msgs, geometry_msgs, sensor_msgs, nav_msgs, tf2_msgs, action_msgs, std_srvs), and the
// emitted set is closed over dependencies, so the output always compiles.
//
// Usage:
//   ros2msggen -o <outDir> [-n <rootNamespace>] [--package <name>] <files-or-dirs…>
// Options:
//   -o <dir>          output directory for the generated .cs files (required)
//   -n <namespace>    root namespace (default Ros2Messages); classes land in <ns>.<package>
//   --package <name>  package name for loose .msg files whose directory doesn't imply one

var inputs = new List<string>();
string? outDir = null, forcedPackage = null;
string ns = "Ros2Messages";

for (int i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "-o" when i + 1 < args.Length: outDir = args[++i]; break;
        case "-n" when i + 1 < args.Length: ns = args[++i]; break;
        case "--package" when i + 1 < args.Length: forcedPackage = args[++i]; break;
        default: inputs.Add(args[i]); break;
    }
}

if (outDir is null || inputs.Count == 0)
{
    Console.Error.WriteLine("usage: ros2msggen -o <outDir> [-n <rootNamespace>] [--package <name>] <files-or-dirs...>");
    return 1;
}

// Collect (fullType, text) from the inputs: messages, services, and actions in separate tables.
var messages = new Dictionary<string, string>();
var services = new Dictionary<string, string>();
var actions = new Dictionary<string, string>();
foreach (string input in inputs)
{
    if (Directory.Exists(input))
    {
        foreach (string pattern in new[] { "*.msg", "*.srv", "*.action" })
            foreach (string file in Directory.EnumerateFiles(input, pattern, SearchOption.AllDirectories))
                Add(file, PackageOf(file));
    }
    else if (File.Exists(input))
    {
        Add(input, forcedPackage ?? PackageOf(input));
    }
    else
    {
        Console.Error.WriteLine($"ros2msggen: no such file or directory: {input}");
        return 1;
    }
}

var catalog = new MsgCatalog(
    fullType => messages.GetValueOrDefault(fullType),
    fullType => services.GetValueOrDefault(fullType),
    fullType => actions.GetValueOrDefault(fullType));

try
{
    Directory.CreateDirectory(outDir);
    List<KeyValuePair<string, string>> emitted =
        CSharpEmitter.EmitClosure(messages.Keys, services.Keys.Concat(EmbeddedMessages.ServiceTypes), actions.Keys, catalog, ns,
            "generated by ros2msggen; do not edit");
    foreach ((string fullType, string code) in emitted)
    {
        string file = Path.Combine(outDir, fullType.Replace('/', '.') + ".g.cs");
        File.WriteAllText(file, code);
        Console.WriteLine($"  {fullType}  -> {file}");
    }
    Console.WriteLine($"{emitted.Count} class(es) written to {Path.GetFullPath(outDir)}");
    return 0;
}
catch (Exception ex)
{
    Console.Error.WriteLine($"ros2msggen: {ex.Message}");
    return 1;
}

void Add(string file, string package)
{
    string fullType = $"{package}/{Path.GetFileNameWithoutExtension(file)}";
    var table = file.EndsWith(".srv", StringComparison.OrdinalIgnoreCase) ? services
        : file.EndsWith(".action", StringComparison.OrdinalIgnoreCase) ? actions
        : messages;
    table[fullType] = File.ReadAllText(file);
}

// ROS layout: <package>/msg/<Name>.msg, <package>/srv/<Name>.srv, <package>/action/<Name>.action
// — the package is the directory above "msg"/"srv"/"action".
static string PackageOf(string file)
{
    var dir = new DirectoryInfo(Path.GetDirectoryName(Path.GetFullPath(file))!);
    if ((string.Equals(dir.Name, "msg", StringComparison.OrdinalIgnoreCase) ||
         string.Equals(dir.Name, "srv", StringComparison.OrdinalIgnoreCase) ||
         string.Equals(dir.Name, "action", StringComparison.OrdinalIgnoreCase)) && dir.Parent is not null)
        dir = dir.Parent;
    return dir.Name;
}
